import json
from tqdm import tqdm
import tempfile
from openai import OpenAI
import asyncio
import argparse
import os
import random
import re
import fcntl
import pdb

api_key = os.getenv("OPENAI_API_KEY")   


def traverse_files_with_oswalk(directory):

    file_paths = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            file_path = os.path.join(root, file)
            file_paths.append(file_path)
    return file_paths

def read_file(paths):
    count_dict = {}
    for path in paths:
        with open(path, 'r') as f:
            valid_records = []
            for line in f:
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue
                # Skip records with reasoning equal to "error"
                if record.get("reasoning") == "error":
                    continue
                valid_records.append(record)
            if valid_records:
                count_dict[os.path.splitext(os.path.basename(path))[0]] = valid_records
    return count_dict

class BaseAnalyzer:
    def __init__(self, args):
        self.args = args
        self.client = OpenAI(api_key=api_key)

    def create_analysis_prompts(self):
        pass
    
    def generate_analysis(self, completion):
        prompt = self.create_analysis_prompts(completion)
        # pdb.set_trace()
        response = self.client.chat.completions.create(
                    model=self.args.model,
                    messages=[
                        {"role": "system", "content": "You are a helpful assistant that analyzes mathematical reasoning."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=self.args.temperature,
                    max_tokens=self.args.max_tokens,
                )
        return response.choices[0].message.content.strip()
    
class NegoEvalAnalyzer(BaseAnalyzer):
    def __init__(self, args):
        super().__init__(args=args)

    def create_analysis_prompts(self, completion):
        
        # Version 1
        prompt = f"""Here is the dialogue:\n'''{completion}'''.

This is a dialogue about diplomacy. Please analyze the quality of this diplomacy conversation by examining whether it mentions specific tactics, relevant units, and centers. 

Carefully review the dialogue and determine if it contains substantive diplomatic content related to:
- Specific tactical moves or strategies
- References to specific units (armies, fleets, etc.)
- Discussion of supply centers or territorial control
or other things related to diplomatic elements.

Based on your analysis, provide a final assessment as either True (if the dialogue contains substantive diplomatic content) or False (if it lacks specific diplomatic elements).

Return your result within the following tags:
<quality>
True or False
</quality>
"""
        return prompt


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # parser.add_argument("--folder", type=str, help="The folder")
    # parser.add_argument("--completion", type=str, help="The chain of thought generated by the model")
    parser.add_argument("--input", required=True, type=str, help="Input file path") 
    parser.add_argument("--output", required=True, type=str, help="Output file path")
    parser.add_argument("--model", default="gpt-4o", type=str, help="The model to use")
    parser.add_argument("--temperature", default=1.0, type=float, help="Temperature of the model")
    parser.add_argument("--max_tokens", default=8192, type=int, help="Maximum tokens to generate")
    args = parser.parse_args()
    
    with open(args.input, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f]
    
    # Generate analysis
    analyzer = NegoEvalAnalyzer(args)
    
    for i in tqdm(range(len(data)), desc="Processing"):
        # all_responses.append(analyzer.generate_analysis(value['intent_dialogue']))
        data[i]['whether_negotiate'] = analyzer.generate_analysis(data[i]['intent_dialogue'])

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)
        
        
# python taskeval_analysis.py --input actual_movement_with_negoeval.jsonl --output negoeval_analysis.json